fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
 
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/pgomersbach/test-profile_base.git"
    profile_jenkins: "https://github.com/pgomersbach/test-profile_jenkins.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    jenkins: "https://github.com/jenkinsci/puppet-jenkins.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    staging: "https://github.com/nanliu/puppet-staging"

  symlinks:
    role_ciserver: "#{source_dir}"
