fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    stings: 'https://github.com/puppetlabs/puppetlabs-strings.git'
 
# role module layout, include profile base and ntp module
    profile_base: "https://github.com/pgomersbach/test-profile_base.git"
    profile_jenkins: "https://github.com/pgomersbach/test-profile_jenkins.git"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    jenkins: "https://github.com/jenkinsci/puppet-jenkins.git"
    java: "https://github.com/puppetlabs/puppetlabs-java.git"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: "2.1.0"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
    archive: "https://github.com/camptocamp/puppet-archive.git"
    jenkins_job_builder: "https://github.com/puppet-community/puppet-jenkins_job_builder.git"

  symlinks:
    role_ciserver: "#{source_dir}"
